services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    volumes:
      - ./frontend:/app
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    depends_on:
      - backend
  
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    tty: true
    volumes:
      - ./backend/app:/app/app
    depends_on:
      - db
    env_file:
      - .env
  
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data: